repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        language_version: python3.11

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: [--max-line-length=88, --extend-ignore=E203,W503]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
      - id: mypy
        additional_dependencies: [types-all]
        args: [--ignore-missing-imports, --strict]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile, black]

  # Spec 040 M3 - Constitutional Compliance Enforcement
  - repo: local
    hooks:
      - id: neo4j-import-ban
        name: Constitutional Compliance - Neo4j Import Ban
        entry: python -c "import sys; import re; violations = []; [violations.append(f) for f in sys.argv[1:] if not any(x in f for x in ['tests/', 'daedalus-gateway', 'backup/deprecated']) and any(re.search(r'^(import neo4j|from neo4j)', open(f).read(), re.MULTILINE) for _ in [1])]; sys.exit(1) if violations and print(f'❌ CONSTITUTIONAL VIOLATION\\n\\nDirect neo4j imports banned per AGENT_CONSTITUTION §2.1, §2.2\\nViolating files: {violations}\\n\\nAll graph access MUST use: from daedalus_gateway import get_graph_channel\\n\\nSee: GRAPH_CHANNEL_MIGRATION_QUICK_REFERENCE.md') else 0"
        language: system
        files: ^backend/src/.*\.py$
        pass_filenames: true
        verbose: true