version: '3.8'

services:
  neo4j:
    image: neo4j:5.15-community
    container_name: neo4j-thoughtseed
    restart: unless-stopped
    environment:
      NEO4J_AUTH: neo4j/thoughtseed123
      NEO4J_PLUGINS: '["apoc", "graph-data-science"]'
      NEO4J_apoc_export_file_enabled: true
      NEO4J_apoc_import_file_enabled: true
      NEO4J_apoc_import_file_use__neo4j__config: true
      NEO4J_ACCEPT_LICENSE_AGREEMENT: yes
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    networks:
      - thoughtseed_network

  # Redis for caching and real-time operations
  redis:
    image: redis:7-alpine
    container_name: redis-thoughtseed
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - thoughtseed_network

volumes:
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local
  neo4j_import:
    driver: local
  neo4j_plugins:
    driver: local
  redis_data:
    driver: local

networks:
  thoughtseed_network:
    driver: bridge